before_install:
  - gem install cocoapods -v '0.33.1'
  - brew update
  - brew upgrade xctool
  - cp Configuration.example.plist Configuration.plist
  
language: swift
script:
  - xctool -workspace allyourmail.xcworkspace -scheme allyourmail -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test